# Labels: define labels for Issues and Pull Requests
labels:
    # type
    - name: 'type: bug'
      description: 'App is not working correctly.'
      color: 'fbca04'
    - name: 'type: discussion'
      description: 'Discussing usage, best practices, questions, etc.'
      color: 'e99695'
    - name: 'type: documentation'
      description: 'Related to improving documentation and the wiki.'
      color: '6addf7'
    - name: 'type: security'
      description: 'Questions, concerns, or suggestions for improving the security of the app.'
      color: '1d76db'
    - name: 'type: enhancement'
      description: 'A new feature suggestion or improvement upon an existing feature.'
      color: '84b6eb'
    - name: 'type: maintenance'
      color: 'fbca04'
    - name: 'type: question'
      color: 'cc317c'
    - name: 'type: feature'
      color: '1d76db'

    #status
    - name: 'status: in progress️'
      description: 'Currently being developed for a future release.'
      color: 'cccccc'
    - name: 'status: on hold'
      description: 'Work has stopped. There may be one or more blockers or needs more information.'
      color: 'e11d21'
    - name: 'status: abandoned'
      color: '000000'
    - name: 'status: accepted'
      color: '009800'
    - name: 'status: available'
      color: 'bfe5bf'
    - name: 'status: blocked'
      color: 'e11d21'
    - name: 'status: completed'
      description: 'This has been addressed in a branch and will be scheduled for release in the assigned milestone.'
      color: '006b75'
    - name: 'status: pending'
      color: 'fef2c0'
    - name: 'status: review needed'
      color: 'fbca04'

    # priority
    - name: 'priority: critical'
      description: 'Critical priority, needs immediate response'
      color: 'e11d21'
    - name: 'priority: high'
      description: 'High priority, needs immediate response'
      color: 'eb6420'
    - name: 'priority: medium'
      description: 'Medium priority'
      color: 'fbca04'
    - name: 'priority: low'
      description: 'Low priority'
      color: '009800'