name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
            - develop

jobs:
    test:
        name: ${{ format('Run Test Node.js {0}', matrix.node) }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['letest', '13', '12']
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Test
              run: |
                  npm install
                  nx run-many --target=test --all
    release:
        name: Semantic Release
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set Node.js letest
              uses: actions/setup-node@v1
              with:
                  node-version: letest

            - name: Release
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              run: |
                  npm install
                  npm run release
              env:
                  GH_TOKEN: ${{secrets.GH_TOKEN}}