name: Release

on:
    push:
        branches:
            - main
            - develop

env:
  CI: true

jobs:
  release:
    name: Build, Release & Publish
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Check Format
        run: npm run format:check
      - name: Lint Workspace & Code
        run: |
          npm run nx -- workspace-lint
          npm run affected:lint -- --all
      - name: Unit Tests
        run: npm run affected:test -- --all
      - name: Build, Release on GitHub & Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release